# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

TORONTO_HOMELESS_SHELTERS = [{'address_1': '70 Gerrard St E',
  'city': 'Toronto',
  'eligibility': 'Women',
  'email': 'info@ssvptoronto.ca',
  'latitude': '43.6600505',
  'location_type': 'Shelter',
  'longitude': '-79.3783115999999',
  'name': "Mary's Home",
  'phone_number': '18773383398',
  'postal_code': 'M5B 1G6',
  'province': 'ON',
  'url': 'http://svdptoronto.org/what-we-do/special-works/residential-housing/womens-Shelters/'},
 {'address_1': '1161 Caledonia Rd',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.7156415',
  'location_type': 'Shelter',
  'longitude': '-79.4666111',
  'name': 'Bethlehem United Shelter',
  'phone_number': '18773383398',
  'postal_code': 'M6A 2W9',
  'province': 'ON',
  'url': 'http://www.fredvictor.org'},
 {'address_1': '86 Lombard St',
  'city': 'Toronto',
  'eligibility': 'Women',
  'email': '',
  'latitude': '43.6522764',
  'location_type': 'Shelter',
  'longitude': '-79.3738781999999',
  'name': "Women's Hostel",
  'phone_number': '18773383398',
  'postal_code': 'M5C 1M3',
  'province': 'ON',
  'url': 'http://www.fredvictor.org'},
 {'address_1': '291 Sherbourne St',
  'city': 'Toronto',
  'eligibility': 'Families',
  'email': '',
  'latitude': '43.6605072',
  'location_type': 'Shelter',
  'longitude': '-79.371793',
  'name': 'Robertson House',
  'phone_number': '18773383398',
  'postal_code': 'M54 2R9',
  'province': 'ON',
  'url': ''},
 {'address_1': '191 Spadina Rd',
  'city': 'Toronto',
  'eligibility': 'Families, Mixed Adults',
  'email': 'info@tchostel.org',
  'latitude': '43.673617',
  'location_type': 'Shelter',
  'longitude': '-79.406284',
  'name': 'Toronto Community Hostel ',
  'phone_number': '18773383398',
  'postal_code': 'M5R 2T9',
  'province': 'ON',
  'url': 'http://www.tchostel.org/'},
 {'address_1': '502 Spadina Ave',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': 'info@scottmission.com',
  'latitude': '43.6586304',
  'location_type': 'Shelter',
  'longitude': '-79.4007404999999',
  'name': 'Scott Mission',
  'phone_number': '18773383398',
  'postal_code': 'M5S 2H1',
  'province': 'ON',
  'url': 'https://www.scottmission.com/'},
 {'address_1': '973 Lansdowne Ave',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': 'conc@conc.ca',
  'latitude': '43.666118',
  'location_type': 'Shelter',
  'longitude': '-79.4461006999999',
  'name': "Men's Hostel",
  'phone_number': '18773383398',
  'postal_code': 'M6H 3Z5',
  'province': 'ON',
  'url': 'http://www.conccommunity.org'},
 {'address_1': '3576 St. Clair Ave E',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': 'admin@homesfirst.on.ca',
  'latitude': '43.717528',
  'location_type': 'Shelter',
  'longitude': '-79.2581093999999',
  'name': 'Homes First Society Scarborough Shelter',
  'phone_number': '18773383398',
  'postal_code': 'M1K 1M2',
  'province': 'ON',
  'url': 'http://www.homesfirst.on.ca'},
 {'address_1': '2808 Dundas St W',
  'city': 'Toronto',
  'eligibility': 'Women',
  'email': '',
  'latitude': '43.6655189',
  'location_type': 'Shelter',
  'longitude': '-79.4631380999999',
  'name': 'Evangeline Residence',
  'phone_number': '18773383398',
  'postal_code': 'M6P 1Y5',
  'province': 'ON',
  'url': 'https://www.torontohhs.org/Shelters/evangeline-residence/'},
 {'address_1': '43 Christie St',
  'city': 'Toronto',
  'eligibility': 'Families',
  'email': 'general@christiestreetrc.com',
  'latitude': '43.665211',
  'location_type': 'Shelter',
  'longitude': '-79.4188482999999',
  'name': 'Christie Refugee Welcome Centre',
  'phone_number': '18773383398',
  'postal_code': 'M6G 3B1',
  'province': 'ON',
  'url': 'http://www.christiestreetrc.com'},
 {'address_1': '1076 Pape Ave',
  'city': 'Toronto',
  'eligibility': 'Youth',
  'email': 'papereception@kennedyhouse.org',
  'latitude': '43.6909102',
  'location_type': 'Shelter',
  'longitude': '-79.3496627999999',
  'name': 'Kennedy House Youth Shelter',
  'phone_number': '18773383398',
  'postal_code': 'M4K 3W5',
  'province': 'ON',
  'url': 'http://www.kennedyhouseyouthShelter.com/'},
 {'address_1': '7 Vanauley St',
  'city': 'Toronto',
  'eligibility': 'Youth',
  'email': 'memberservices@ymcagta.org',
  'latitude': '43.648883',
  'location_type': 'Shelter',
  'longitude': '-79.398229',
  'name': 'Vanauley Street',
  'phone_number': '18773383398',
  'postal_code': 'M5T 2V9',
  'province': 'ON',
  'url': 'https://ymcagta.org/find-a-y/toronto-vanauley-street-ymca-centre'},
 {'address_1': '850 Bloor St W',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': 'conc@conc.ca',
  'latitude': '43.662443',
  'location_type': 'Shelter',
  'longitude': '-79.424144',
  'name': "Men's South Hostel",
  'phone_number': '18773383398',
  'postal_code': 'M6G 1M2',
  'province': 'ON',
  'url': 'http://www.conccommunity.org'},
 {'address_1': '702 Kennedy Rd',
  'city': 'Toronto',
  'eligibility': 'Women',
  'email': 'admin@homesfirst.on.ca',
  'latitude': '43.7279261',
  'location_type': 'Shelter',
  'longitude': '-79.2676743',
  'name': 'Kennedy Shelter',
  'phone_number': '18773383398',
  'postal_code': 'M1K 2B5',
  'province': 'ON',
  'url': 'http://www.homesfirst.on.ca'},
 {'address_1': '129 Peter St',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.6486966',
  'location_type': 'Shelter',
  'longitude': '-79.3932737',
  'name': 'Streets to Homes Assessment and Referral Centre (SHARC)',
  'phone_number': '18773383398',
  'postal_code': 'M5V 2H3',
  'province': 'ON',
  'url': ''},
 {'address_1': '723 Queen St W',
  'city': 'Toronto',
  'eligibility': 'Women',
  'email': '',
  'latitude': '43.6464893',
  'location_type': 'Shelter',
  'longitude': '-79.4063380999999',
  'name': 'Florence Booth House',
  'phone_number': '18773383398',
  'postal_code': 'M6J 1E6',
  'province': 'ON',
  'url': 'http://www.florenceboothhouse.com'},
 {'address_1': '20 Gerrard St E',
  'city': 'Toronto',
  'eligibility': 'Youth',
  'email': 'general@covenanthouse.ca',
  'latitude': '43.6594024',
  'location_type': 'Shelter',
  'longitude': '-79.3814883999999',
  'name': 'Covenant Gerrard Street',
  'phone_number': '18773383398',
  'postal_code': 'M5B 2P3',
  'province': 'ON',
  'url': 'http://www.covenanthousetoronto.ca'},
 {'address_1': '1322 Bloor St W',
  'city': 'Toronto',
  'eligibility': 'Women',
  'email': 'admin@homesfirst.on.ca',
  'latitude': '43.6583716',
  'location_type': 'Shelter',
  'longitude': '-79.4432342',
  'name': "Savard's Women's Shelter",
  'phone_number': '18773383398',
  'postal_code': 'M6H 1P2',
  'province': 'ON',
  'url': 'http://www.homesfirst.on.ca'},
 {'address_1': '23 Grange Rd',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.6520518',
  'location_type': 'Shelter',
  'longitude': '-79.3914743',
  'name': 'University Settlement Recreation Centre',
  'phone_number': '18773383398',
  'postal_code': 'M5T 1C3',
  'province': 'ON',
  'url': 'http://www.universitysettlement.ca/out-of-the-cold'},
 {'address_1': '80 Woodlawn Ave E',
  'city': 'Toronto',
  'eligibility': 'Women, Youth',
  'email': '1intake@ywcatoronto.org',
  'latitude': '43.6845473',
  'location_type': 'Shelter',
  'longitude': '-79.3899842',
  'name': 'Woodlawn',
  'phone_number': '18773383398',
  'postal_code': 'M4T 1C1',
  'province': 'ON',
  'url': 'https://www.ywcatoronto.org/'},
 {'address_1': '6 Warrendale Ct',
  'city': 'Etobicoke',
  'eligibility': 'Youth',
  'email': 'communications@yws.on.ca',
  'latitude': '43.7362929',
  'location_type': 'Shelter',
  'longitude': '-79.5804269',
  'name': 'Youth Without Shelter ',
  'phone_number': '18773383398',
  'postal_code': 'M9V 1P9',
  'province': 'ON',
  'url': 'https://www.yws.on.ca/'},
 {'address_1': '1229 Ellesmere Rd',
  'city': 'Toronto',
  'eligibility': 'Families',
  'email': '',
  'latitude': '43.7682821999999',
  'location_type': 'Shelter',
  'longitude': '-79.2674465999999',
  'name': 'Birkdale Residence',
  'phone_number': '18773383398',
  'postal_code': 'M1P 4V8',
  'province': 'ON',
  'url': ''},
 {'address_1': '2671 Islington Avenue',
  'city': 'Toronto',
  'eligibility': 'Men, Women',
  'email': '',
  'latitude': '43.739305',
  'location_type': 'Shelter',
  'longitude': '-79.56588',
  'name': 'Salvation Army Islington Seniors',
  'phone_number': '18773383398',
  'postal_code': 'M9V 2X6',
  'province': 'ON',
  'url': ''},
 {'address_1': '2714 Danforth Ave',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': 'haydar.shouly@dixonhall.org',
  'latitude': '43.6891159',
  'location_type': 'Shelter',
  'longitude': '-79.2982554999999',
  'name': 'Heyworth House',
  'phone_number': '18773383398',
  'postal_code': 'M4C 1L7',
  'province': 'ON',
  'url': 'http://www.dixonhall.org'},
 {'address_1': '349 George St',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': 'harvey.stein@dixonhall.org',
  'latitude': '43.6601444',
  'location_type': 'Shelter',
  'longitude': '-79.3743056',
  'name': 'The School House',
  'phone_number': '18773383398',
  'postal_code': 'M5A 2N2',
  'province': 'ON',
  'url': 'http://www.dixonhall.org'},
 {'address_1': '95 Wellesley St E',
  'city': 'Toronto',
  'eligibility': 'Youth',
  'email': 'info@turningpoint.ca',
  'latitude': '43.6658642',
  'location_type': 'Shelter',
  'longitude': '-79.3792151999999',
  'name': 'Turning Point',
  'phone_number': '18773383398',
  'postal_code': 'M4Y 2X9',
  'province': 'ON',
  'url': 'http://turningpoint.ca/'},
 {'address_1': '360 Lesmill Rd',
  'city': 'Toronto',
  'eligibility': 'Youth',
  'email': 'info@evas.ca',
  'latitude': '43.7633708',
  'location_type': 'Shelter',
  'longitude': '-79.3608998999999',
  'name': "Eva's Place",
  'phone_number': '18773383398',
  'postal_code': 'M3B 2T5',
  'province': 'ON',
  'url': 'http://www.evas.ca'},
 {'address_1': '525 Bloor St E',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': 'stsimonsShelter@bellnet.ca',
  'latitude': '43.6719373',
  'location_type': 'Shelter',
  'longitude': '-79.3740541999999',
  'name': "St.Simon's Shelter",
  'phone_number': '18773383398',
  'postal_code': 'M4W 1J1',
  'province': 'ON',
  'url': ''},
 {'address_1': '1430 Gerrard St E',
  'city': 'Toronto',
  'eligibility': 'Families',
  'email': 'reception@reddoorShelter.ca',
  'latitude': '43.672485',
  'location_type': 'Shelter',
  'longitude': '-79.322398',
  'name': 'Red Door Family Shelter',
  'phone_number': '18773383398',
  'postal_code': 'M4M 1J2',
  'province': 'ON',
  'url': 'https://www.reddoorShelter.ca'},
 {'address_1': '674 Dundas St W',
  'city': 'Toronto',
  'eligibility': 'Women',
  'email': '',
  'latitude': '43.6518818',
  'location_type': 'Shelter',
  'longitude': '-79.4036945',
  'name': "Women's Residence",
  'phone_number': '18773383398',
  'postal_code': 'M5H 1H9',
  'province': 'ON',
  'url': ''},
 {'address_1': '339 George St',
  'city': 'Toronto',
  'eligibility': 'Men, Mixed Adults',
  'email': '',
  'latitude': '43.659956',
  'location_type': 'Shelter',
  'longitude': '-79.3742651999999',
  'name': 'Seaton House',
  'phone_number': '18773383398',
  'postal_code': 'M5A 2N2',
  'province': 'ON',
  'url': ''},
 {'address_1': '412 Queen St East',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': 'info@goodshepherd.ca',
  'latitude': '43.6561511',
  'location_type': 'Shelter',
  'longitude': '-79.3625223999999',
  'name': 'Good Shepherd Centre',
  'phone_number': '18773383398',
  'postal_code': 'M5A 1T3',
  'province': 'ON',
  'url': 'http://www.goodshepherd.ca'},
 {'address_1': '25 Canterbury Pl',
  'city': 'Toronto',
  'eligibility': 'Youth',
  'email': 'info@evas.ca',
  'latitude': '43.7728179',
  'location_type': 'Shelter',
  'longitude': '-79.4147577',
  'name': "Eva's Satellite",
  'phone_number': '18773383398',
  'postal_code': 'M3N 0E3',
  'province': 'ON',
  'url': 'http://www.evas.ca'},
 {'address_1': '616 Vaughan Rd',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': 'info@thecornerstone.ca',
  'latitude': '43.6919622',
  'location_type': 'Shelter',
  'longitude': '-79.4398588',
  'name': 'The Cornerstone Place',
  'phone_number': '18773383398',
  'postal_code': 'M6C 2R5',
  'province': 'ON',
  'url': 'http://www.thecornerstone.ca'},
 {'address_1': '107 Jarvis St',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': 'frontline@thegateway.ca',
  'latitude': '43.6523669',
  'location_type': 'Shelter',
  'longitude': '-79.3722725',
  'name': 'The Gateway',
  'phone_number': '18773383398',
  'postal_code': 'M5C 2H4',
  'province': 'ON',
  'url': 'http://www.thegateway.ca'},
 {'address_1': '60 Newcastle St',
  'city': 'Toronto',
  'eligibility': 'Women',
  'email': 'info@ssvptoronto.ca',
  'latitude': '43.6180295',
  'location_type': 'Shelter',
  'longitude': '-79.4973215',
  'name': 'Elisa House',
  'phone_number': '18773383398',
  'postal_code': 'M8Y 1A3',
  'province': 'ON',
  'url': 'http://svdptoronto.org/what-we-do/special-works/residential-housing/womens-Shelters/'},
 {'address_1': '422 Gilbert Ave',
  'city': 'Toronto',
  'eligibility': 'Youth',
  'email': 'info@horizonsforyouth.org',
  'latitude': '43.6893531',
  'location_type': 'Shelter',
  'longitude': '-79.4623881999999',
  'name': 'Horizons for Youth',
  'phone_number': '18773383398',
  'postal_code': 'M6E 4X3',
  'province': 'ON',
  'url': 'http://www.horizons4youth.org/'},
 {'address_1': '100 Lippincott St',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': 'info@costi.org',
  'latitude': '43.6576775',
  'location_type': 'Shelter',
  'longitude': '-79.4070466',
  'name': 'Reception Centre',
  'phone_number': '18773383398',
  'postal_code': 'M5S 2P1',
  'province': 'ON',
  'url': 'http://www.costi.org/'},
 {'address_1': '4222 Kingston Rd',
  'city': 'Toronto',
  'eligibility': 'Families',
  'email': '',
  'latitude': '43.7607677',
  'location_type': 'Shelter',
  'longitude': '-79.1967389',
  'name': 'Family Residence',
  'phone_number': '18773383398',
  'postal_code': 'M1E 2M6',
  'province': 'ON',
  'url': ''},
 {'address_1': '87 Pembroke St',
  'city': 'Toronto',
  'eligibility': 'Women',
  'email': 'info@streethaven.com',
  'latitude': '43.6592425',
  'location_type': 'Shelter',
  'longitude': '-79.3724295999999',
  'name': 'Street Haven',
  'phone_number': '18773383398',
  'postal_code': 'M5A 2N9',
  'province': 'ON',
  'url': 'http://www.streethaven.org/'},
 {'address_1': '135 Sherbourne St',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': '',
  'latitude': '43.6550275',
  'location_type': 'Shelter',
  'longitude': '-79.3692151',
  'name': 'Maxwell Meighen Centre',
  'phone_number': '18773383398',
  'postal_code': 'M5A 2R5',
  'province': 'ON',
  'url': 'http://www.maxwellmeighen.ca'},
 {'address_1': '101 Ontario St',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': 'info@sojournhouse.org',
  'latitude': '43.6544994',
  'location_type': 'Shelter',
  'longitude': '-79.366777',
  'name': 'Sojourn House',
  'phone_number': '18773383398',
  'postal_code': 'M5A 2V2',
  'province': 'ON',
  'url': 'http://www.sojournhouse.org'},
 {'address_1': '29 Leslie St',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': '',
  'latitude': '43.661969',
  'location_type': 'Shelter',
  'longitude': '-79.3295039999999',
  'name': 'New Hope Leslieville',
  'phone_number': '18773383398',
  'postal_code': 'M4M 3C3',
  'province': 'ON',
  'url': 'https://www.torontohhs.org/Shelters/hope-Shelter/'},
 {'address_1': '348 Davenport Road',
  'city': 'Toronto',
  'eligibility': 'Women, Youth',
  'email': '',
  'latitude': '43.675281',
  'location_type': 'Shelter',
  'longitude': '-79.401442',
  'name': 'YWCA - 348 Davenport Road',
  'phone_number': '18773383398',
  'postal_code': 'M5R 1K6',
  'province': 'ON',
  'url': ''},
 {'address_1': '14 Vaughan Rd',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': 'general@nameres.org',
  'latitude': '43.6814823129631',
  'location_type': 'Shelter',
  'longitude': '-79.418172456414',
  'name': 'Na-Me-Res',
  'phone_number': '18773383398',
  'postal_code': 'M6G 2N1',
  'province': 'ON',
  'url': 'https://www.nameres.org'},
 {'address_1': '805A Wellington St W',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': 'admin@homesfirst.on.ca',
  'latitude': '43.640808',
  'location_type': 'Shelter',
  'longitude': '-79.4103663999999',
  'name': 'Strachan House',
  'phone_number': '18773383398',
  'postal_code': 'M5V 1G8',
  'province': 'ON',
  'url': 'http://www.homesfirst.on.ca'}]



TORONTO_OUT_OF_THE_COLD_CENTERS = [{'address_1': '2850 Bloor St W',
  'city': 'Toronto',
  'eligibility': 'Men',
  'email': '',
  'latitude': '43.648914',
  'location_type': 'Out of the Cold',
  'longitude': '-79.504705',
  'name': "All Saints' (Kingsway) Anglican Church",
  'phone_number': '4162070791',
  'postal_code': 'M8X 1B2',
  'province': 'ON',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '100 Elder St',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.760631',
  'location_type': 'Out of the Cold',
  'longitude': '-79.453551',
  'name': 'Beth Emeth ',
  'phone_number': '4162070791',
  'postal_code': 'M3H 5G7',
  'province': 'ON',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '1445 Eglinton Ave W',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.698258',
  'location_type': 'Out of the Cold',
  'longitude': '-79.438118',
  'name': 'Beth Sholom ',
  'phone_number': '4162070791',
  'postal_code': 'M6C 2E6',
  'province': 'ON',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '80 Blythwood Rd',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.717584',
  'location_type': 'Out of the Cold',
  'longitude': '-79.398082',
  'name': 'Blythwood Road Baptist Church',
  'phone_number': '4162070791',
  'postal_code': 'M4N 1A4',
  'province': 'ON',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '450 Dundas St W',
  'city': 'ON',
  'eligibility': 'Men',
  'email': '',
  'latitude': '43.653484',
  'location_type': 'Out of the Cold',
  'longitude': '-79.395917',
  'name': 'Chinese Gospel',
  'phone_number': '4162070791',
  'postal_code': 'M5T 1G7',
  'province': '',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '310 Danforth Ave  Toronto',
  'city': '',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.677472',
  'location_type': 'Out of the Cold',
  'longitude': '-79.353723',
  'name': 'Eastminster United ',
  'phone_number': '4162070791',
  'postal_code': 'M4K 1N6',
  'province': '',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '552 Adelaide St W  Toronto',
  'city': '',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.64545',
  'location_type': 'Out of the Cold',
  'longitude': '-79.40243',
  'name': 'Evangell Hall',
  'phone_number': '4162070791',
  'postal_code': 'M5V 3W8',
  'province': '',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '729 St Clair Ave W, Bsmt',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.681239',
  'location_type': 'Out of the Cold',
  'longitude': '-79.427246',
  'name': "First Interfaith at St Matthew's",
  'phone_number': '4162070791',
  'postal_code': 'M6C 1B2',
  'province': '',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '1950 Bathurst St',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.698295',
  'location_type': 'Out of the Cold',
  'longitude': '-79.425272',
  'name': 'Holy Blossom Temple',
  'phone_number': '4162070791',
  'postal_code': 'M5P 3K9',
  'province': 'ON',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '2575 Midland Ave',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.786796',
  'location_type': 'Out of the Cold',
  'longitude': '-79.278609',
  'name': 'Knox United',
  'phone_number': '4162070791',
  'postal_code': 'M1S 1R3',
  'province': '',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '140 Wineva Ave  Toronto',
  'city': '',
  'eligibility': 'Mixed Adult',
  'email': '',
  'latitude': '43.6715979',
  'location_type': 'Out of the Cold',
  'longitude': '-79.2985661',
  'name': 'Out of the Cold in the Beach, Beach United Church',
  'phone_number': '4162070791',
  'postal_code': 'M4E 2T4',
  'province': '',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '1099 Danforth Ave  Toronto',
  'city': '',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.680783',
  'location_type': 'Out of the Cold',
  'longitude': '-79.334987',
  'name': "St Brigid's Annex",
  'phone_number': '4162070791',
  'postal_code': 'M4J 1M5',
  'province': '',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '156 Sixth St  Toronto',
  'city': '',
  'eligibility': 'Men',
  'email': '',
  'latitude': '43.602273',
  'location_type': 'Out of the Cold',
  'longitude': '-79.504698',
  'name': "Lakeshore at St Margaret's Church",
  'phone_number': '4162070791',
  'postal_code': 'M8V 3A5',
  'province': '',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '3962 Bloor St W  Toronto',
  'city': '',
  'eligibility': 'Men',
  'email': '',
  'latitude': '43.638787',
  'location_type': 'Out of the Cold',
  'longitude': '-79.548753',
  'name': 'St Matthew Our Lady of Peace',
  'phone_number': '4162070791',
  'postal_code': 'M9B 1M3',
  'province': '',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '139 McCaul St  Toronto',
  'city': '',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.654885',
  'location_type': 'Out of the Cold',
  'longitude': '-79.391543',
  'name': "St Patrick's",
  'phone_number': '4162070791',
  'postal_code': 'M5T 1W3',
  'province': '',
  'url': 'http://www.dixonhall.org/housingservices'},
 {'address_1': '1585 Yonge St',
  'city': 'Toronto',
  'eligibility': 'Mixed Adults',
  'email': '',
  'latitude': '43.690527',
  'location_type': 'Out of the Cold',
  'longitude': '-79.39423',
  'name': 'Yorkminster Park Baptist',
  'phone_number': '4162070791',
  'postal_code': 'M4T 1Z9',
  'province': 'ON',
  'url': 'http://www.dixonhall.org/housingservices'}]


TORONTO_HOUSING_HELP = [{'address_1': '4155 Sheppard Ave E Ste 100  Toronto',
'city': '',
'eligibility': 'Men, Women, Youth, Seniors, Families',
'email': 'info@agincourtcommunityservices.com',
'latitude': '43.784559',
'location_type': 'Housing Help',
'longitude': '-79.280908',
'name': 'Housing Help Program',
'phone_number': '4163216912235236',
'postal_code': 'M1S 1T4',
'province': '',
'url': 'http://www.agincourtcommunityservices.com'},
{'address_1': '21 Panorama Crt, Ste 14  Toronto',
'city': ',',
'eligibility': 'Men, Women, Youth, Seniors, Families',
'email': 'ans@albionservices.ca',
'latitude': '43.7463319',
'location_type': 'Housing Help',
'longitude': '-79.5835071',
'name': 'North Etobicoke Housing Help Centre',
'phone_number': '4167403704',
'postal_code': 'M9V 4E3',
'province': '',
'url': 'http://www.albionneighbourhoodservices.ca'},
{'address_1': '185 Fifth St  Toronto',
'city': '',
'eligibility': 'Men, Women, Youth, Seniors, Families',
'email': 'ans@albionservices.ca',
'latitude': '43.6035237',
'location_type': 'Housing Help',
'longitude': '-79.5056595',
'name': 'South Etobicoke Housing Help Centre',
'phone_number': '4162525990',
'postal_code': 'M8V 2Z5',
'province': '',
'url': 'http://www.albionneighbourhoodservices.ca'},
{'address_1': '1700 Wilson Ave, Ste 114  Toronto',
'city': '',
'eligibility': 'Men, Women, Youth, Seniors, Families',
'email': 'nyork@costi.org ',
'latitude': '43.7212592',
'location_type': 'Housing Help',
'longitude': '-79.5141807',
'name': 'North York Housing Help Centre',
'phone_number': '4162440480',
'postal_code': 'M3L 1A3',
'province': '',
'url': 'http://www.costi.org'},
{'address_1': '1350 Danforth Ave  Toronto',
'city': '',
'eligibility': 'Men, Women, Youth, Seniors, Families',
'email': 'eyhhc@eyetfrp.ca',
'latitude': '43.6772836',
'location_type': 'Housing Help',
'longitude': '-79.3554913',
'name': 'East York Housing Help Centre',
'phone_number': '4166989306',
'postal_code': 'M4J 1M9',
'province': '',
'url': 'http://eyetfrp.ca'},
{'address_1': '2500 Lawrence Ave E  Toronto',
'city': '',
'eligibility': 'Men, Women, Youth, Seniors, Families',
'email': 'info@thhc.org',
'latitude': '43.7515292',
'location_type': 'Housing Help',
'longitude': '-79.2697946',
'name': 'Housing Help Centre, The',
'phone_number': '4162858070',
'postal_code': 'M1P 2R7',
'province': '',
'url': 'http://www.thhc.org'},
{'address_1': '10 Gateway Blvd  Toronto',
'city': '',
'eligibility': 'Men, Women, Youth, Seniors, Families',
'email': 'info@tno-toronto.org',
'latitude': '43.7097748',
'location_type': 'Housing Help',
'longitude': '-79.334874',
'name': 'Flemingdon Park Housing Help Centre',
'phone_number': '4164242900',
'postal_code': 'M3C 3A1',
'province': '',
'url': 'http://www.tno-toronto.org'},
{'address_1': '1032 Bloor St W  Toronto',
'city': '',
'eligibility': 'Men, Women, Youth, Seniors, Families',
'email': '',
'latitude': '43.6608244',
'location_type': 'Housing Help',
'longitude': '-79.4337016',
'name': 'West Toronto Housing Help Services',
'phone_number': '4165310841',
'postal_code': 'M6R 1M2',
'province': '',
'url': 'http://www.wtcls.org  '},
{'address_1': '650 Queen St E  Toronto',
'city': '',
'eligibility': 'Men, Women, Youth, Seniors, Families',
'email': 'info@woodgreen.org ',
'latitude': '43.6585476',
'location_type': 'Housing Help',
'longitude': '-79.3541438',
'name': 'WoodGreen Housing Help Centre',
'phone_number': '41664560001891',
'postal_code': 'M4M 1G5',
'province': '',
'url': 'http://www.woodgreen.org'},
{'address_1': '1651 Keele St  Toronto',
'city': '',
'eligibility': 'Men, Women, Youth, Seniors, Families',
'email': '',
'latitude': '43.6834521',
'location_type': 'Housing Help',
'longitude': '-79.4741372',
'name': 'Housing Help Program',
'phone_number': '41665354001306',
'postal_code': 'M6M 3W2',
'province': '',
'url': 'http://www.unisonhcs.org'}]

TORONTO_RESPITE_SITES = [{'address_1': "180 Princes' Blvd  Toronto",
'city': '',
'eligibility': 'Mixed Adults',
'email': 'admin@homesfirst.on.ca',
'latitude': '43.632714',
'location_type': '24 Hour Respite Sites',
'longitude': '-79.420359',
'name': 'Queen Elizabeth Respite',
'phone_number': '4163384766',
'postal_code': 'M6K 3C3',
'province': '',
'url': 'http://www.homesfirst.on.ca'},
{'address_1': '705 Progress Ave  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'warden@wardenwoods.com',
'latitude': '43.77318',
'location_type': '24 Hour Respite Sites',
'longitude': '-79.246023',
'name': 'Progress Avenue',
'phone_number': '4163384766',
'postal_code': 'M1H 2X1',
'province': '',
'url': 'http://www.wardenwoods.com'},
{'address_1': '323 Dundas St E  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'info@margarets.ca',
'latitude': '43.658316',
'location_type': '24 Hour Respite Sites',
'longitude': '-79.370103',
'name': 'Downtown East',
'phone_number': '4163384766',
'postal_code': 'M5A 2A2',
'province': '',
'url': 'http://www.margarets.ca'},
{'address_1': '201 Cowan Ave  Toronto',
'city': '',
'eligibility': 'Women',
'email': 'info@dixonhall.org',
'latitude': '43.640776',
'location_type': '24 Hour Respite Sites',
'longitude': '-79.432294',
'name': 'Cowan Avenue',
'phone_number': '4163384766',
'postal_code': 'M6K 2N7',
'province': '',
'url': 'http://www.dixonhall.org'},
{'address_1': '354 George St  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'admin@homesfirst.on.ca',
'latitude': '43.659139',
'location_type': '24 Hour Respite Sites',
'longitude': '-79.374355',
'name': '354 George Street',
'phone_number': '4163384766',
'postal_code': 'M5A 2N3',
'province': '',
'url': 'http://www.homesfirst.on.ca'},
{'address_1': '21 Park Rd  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'info@margarets.ca',
'latitude': '43.672096',
'location_type': '24 Hour Respite Sites',
'longitude': '-79.384462',
'name': 'Park Road ',
'phone_number': '4163384766',
'postal_code': 'M4W 2N1',
'province': '',
'url': 'http://www.margarets.ca'},
{'address_1': '545 Lake Shore Blvd W  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': '',
'latitude': '43.63649',
'location_type': '24 Hour Respite Sites',
'longitude': '-79.39874',
'name': 'Lake Shore West',
'phone_number': '4163384766',
'postal_code': 'M5V 1A3',
'province': '',
'url': 'http://www.fredvictor.org'},
{'address_1': '25 Augusta Ave  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'stfelixcentre@rogers.com',
'latitude': '43.649078',
'location_type': '24 Hour Respite Sites',
'longitude': '-79.3995',
'name': 'St Felix Centre - 25 Augusta',
'phone_number': '4163384766',
'postal_code': 'M5T 2K7',
'province': '',
'url': 'http://www.stfelixcentre.ca'},
{'address_1': '69 Fraser Ave  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'respite2@stfelixcentre.com',
'latitude': '43.638484',
'location_type': '24 Hour Respite Sites',
'longitude': '-79.424373',
'name': 'St Felix Centre - 69 Fraser',
'phone_number': '4163384766',
'postal_code': 'M6K 1E9',
'province': '',
'url': 'http://www.stfelixcentre.ca'},
{'address_1': '129 Peter St',
'city': 'Toronto',
'eligibility': 'Mixed Adults',
'email': '',
'latitude': '43.6486966',
'location_type': '24 Hour Respite Sites',
'longitude': '-79.3932737',
'name': 'Streets to Homes Assessment and Referral Centre (SHARC)',
'phone_number': '4163920090',
'postal_code': 'M5V 2H3',
'province': 'ON',
'url': ''}]

TORONTO_DROP_INS = [{'address_1': '519 Church St  Toronto',
'city': '',
'eligibility': 'Mixed Adults (LGBTQ)',
'email': 'info@The519.org',
'latitude': '43.666532',
'location_type': 'Drop-in',
'longitude': '-79.38097',
'name': 'Sunday Drop-in & Meal Trans',
'phone_number': '4163926874',
'postal_code': 'M4Y 2C9',
'province': '',
'url': 'http://www.The519.org'},
{'address_1': '4155 Sheppard Ave E  Toronto , Ste 100',
'city': 'ON',
'eligibility': 'Mixed Adults',
'email': 'info@agincourtcommunityservices.com',
'latitude': '43.784559',
'location_type': 'Drop-in',
'longitude': '-79.280908',
'name': 'Scarborough Drop-in North',
'phone_number': '4163216912',
'postal_code': '1T4 ',
'province': 'M1S',
'url': 'http://www.agincourtcommunityservices.com'},
{'address_1': '850 Bloor St W  Toronto ',
'city': 'ON',
'eligibility': 'Mixed Adults, Men, Women, Seniors',
'email': 'conc@conc.ca',
'latitude': '43.662421',
'location_type': 'Drop-in',
'longitude': '-79.424201',
'name': 'Drop-in and Food Access Program',
'phone_number': '4167928941',
'postal_code': '1M2 ',
'province': 'M6G',
'url': 'http://www.conccommunity.org'},
{'address_1': '40 Oak St  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'crc@tcrc.ca',
'latitude': '43.661377',
'location_type': 'Drop-in',
'longitude': '-79.365151',
'name': 'CRC',
'phone_number': '4163634234',
'postal_code': 'M5A 2C6',
'province': '',
'url': 'http://www.tcrc.ca'},
{'address_1': '1900 Davenport Rd  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'info@dpnchc.ca',
'latitude': '43.6707',
'location_type': 'Drop-in',
'longitude': '-79.4548',
'name': 'Davenport Perth Neighbourhood and Community Health Centre',
'phone_number': '4166568025',
'postal_code': 'M6N 1B7',
'province': '',
'url': 'http://www.dpnchc.com'},
{'address_1': '552 Adelaide St W  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'information@evangelhall.ca',
'latitude': '43.64545',
'location_type': 'Drop-in',
'longitude': '-79.40243',
'name': 'Adult Drop-in Centre',
'phone_number': '4165043563',
'postal_code': 'M5V 3W8',
'province': '',
'url': 'http://www.evangelhall.ca'},
{'address_1': 'Adelaide Resource Centre for Women, 67 Adelaide St E  Toronto ',
'city': 'ON',
'eligibility': 'Women',
'email': 'wdp@fredvictor.org',
'latitude': '43.650986',
'location_type': 'Drop-in',
'longitude': '-79.375299',
'name': '24-Hour Drop-in for Women',
'phone_number': '4163929292',
'postal_code': '1K6 ',
'province': 'M5C',
'url': 'http://www.fredvictor.org'},
{'address_1': '412 Queen St E  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'info@goodshepherd.ca',
'latitude': '43.656151',
'location_type': 'Drop-in',
'longitude': '-79.362522',
'name': 'Good Shepherd Centre Drop-in',
'phone_number': '4168693619',
'postal_code': 'M5A 1T3',
'province': '',
'url': 'http://www.goodshepherd.ca'},
{'address_1': '170 Jarvis St  Toronto',
'city': '',
'eligibility': 'Men (50+)',
'email': 'info@haventoronto.ca',
'latitude': '43.655562',
'location_type': 'Drop-in',
'longitude': '-79.374328',
'name': 'Haven Toronto',
'phone_number': '4163665377',
'postal_code': 'M5B 2B7',
'province': '',
'url': 'http://www.haventoronto.ca'},
{'address_1': '185 Fifth St  Toronto',
'city': '',
'eligibility': 'Mixed Adults, Women',
'email': 'russf@lampchc.org',
'latitude': '43.603741',
'location_type': 'Drop-in',
'longitude': '-79.50401',
'name': 'LAMP Community Health Centre',
'phone_number': '4162526471',
'postal_code': 'M8V 2Z5',
'province': '',
'url': 'http://www.lampchc.org'},
{'address_1': '655 Bloor St W  Toronto ',
'city': 'ON',
'eligibility': 'Youth (Indigenous,16-24)',
'email': 'info@nativechild.org',
'latitude': '43.664107',
'location_type': 'Drop-in',
'longitude': '-79.415456',
'name': 'Native Youth Resource Centre, Drop-in',
'phone_number': '4169698510',
'postal_code': '1L1 ',
'province': 'M6G',
'url': 'http://www.nativechild.org/youth/drop-in-centre'},
{'address_1': '1499 Queen St W  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'info@parc.on.ca',
'latitude': '43.639648',
'location_type': 'Drop-in',
'longitude': '-79.440557',
'name': 'PARC Drop-in ',
'phone_number': '4165372262',
'postal_code': 'M6R 1A3',
'province': '',
'url': 'http://parc.on.ca'},
{'address_1': '333 Sherbourne St, 2nd Fl  Toronto',
'city': '',
'eligibility': 'Youth (LGBTQ, 14-29)',
'email': 'soy@sherbourne.on.ca',
'latitude': '43.662388',
'location_type': 'Drop-in',
'longitude': '-79.372209',
'name': 'Supporting Our Youth (SOY)',
'phone_number': '4163244180',
'postal_code': 'M5A 2S5',
'province': '',
'url': 'http://www.soytoronto.org'},
{'address_1': '962 Bloor St W  Toronto',
'city': '',
'eligibility': 'Women',
'email': 'general_info@sistering.org',
'latitude': '43.661416',
'location_type': 'Drop-in',
'longitude': '-79.428785',
'name': 'Drop-in Centre Bloor Street',
'phone_number': '4169269762',
'postal_code': 'M6H 1L6',
'province': '',
'url': 'http://www.sistering.org'},
{'address_1': '155 Broadview Ave  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'info@stjohnsmission.org',
'latitude': '43.660472',
'location_type': 'Drop-in',
'longitude': '-79.350328',
'name': 'Community Drop-in',
'phone_number': '4164661357',
'postal_code': 'M4M 2E9',
'province': '',
'url': 'http://www.stjohnsmission.org'},
{'address_1': '260 Augusta Ave  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': '260admin@ststephenshouse.com',
'latitude': '43.65648',
'location_type': 'Drop-in',
'longitude': '-79.402996',
'name': 'Corner Drop-in',
'phone_number': '41692521032240',
'postal_code': 'M5T 2L9',
'province': '',
'url': 'http://www.sschto.ca'},
{'address_1': '1884 Davenport Rd, Rear Entrance  Toronto',
'city': '',
'eligibility': 'Mixed Adults ',
'email': 'general@thestop.org',
'latitude': '43.670859',
'location_type': 'Drop-in',
'longitude': '-79.45382',
'name': 'Stop: Community Food Centre',
'phone_number': '4166527867',
'postal_code': 'M6N 4Y2',
'province': '',
'url': 'http://www.thestop.org'},
{'address_1': '2468 Eglinton Ave W  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': 'thewitt@symewoolner.org',
'latitude': '43.691929',
'location_type': 'Drop-in',
'longitude': '-79.468411',
'name': "Jane's Place Drop-In",
'phone_number': '4167664634',
'postal_code': 'M6M 5E2',
'province': '',
'url': 'http://www.symewoolner.org'},
{'address_1': '439 Dundas St E  Toronto',
'city': '',
'eligibility': 'Mixed Adults (Indigenous)',
'email': 'cdo@councilfire.ca',
'latitude': '43.65928',
'location_type': 'Drop-in',
'longitude': '-79.366308',
'name': 'Gathering Place ',
'phone_number': '4163604350',
'postal_code': 'M5A 2B1',
'province': '',
'url': 'http://www.councilfire.ca'},
{'address_1': '588 Queen St W  Toronto',
'city': '',
'eligibility': 'Mixed Adults',
'email': ' info@westnh.org',
'latitude': '43.647423',
'location_type': 'Drop-in',
'longitude': '-79.404281',
'name': 'Meeting Place',
'phone_number': '4165327586',
'postal_code': 'M6J 1E3',
'province': '',
'url': 'http://www.westnh.org/'},
{'address_1': '2017 Weston Rd  Toronto',
'city': '',
'eligibility': 'Mixed Adults, Men, Women, Seniors',
'email': 'info@wknc.ca',
'latitude': '43.701372',
'location_type': 'Drop-in',
'longitude': '-79.520101',
'name': 'Weston King Neighbourhood Centre',
'phone_number': '4162419898',
'postal_code': 'M9N 1X2',
'province': '',
'url': 'http://www.wknc.ca'},
{'address_1': '729 St. Clair Ave W, Bsmt',
'city': 'Toronto',
'eligibility': 'Mixed Adults',
'email': 'wychwoodopendoor@gmail.com',
'latitude': '43.681239',
'location_type': 'Drop-in',
'longitude': '-79.427246',
'name': 'Drop-in Centre',
'phone_number': '6473523513',
'postal_code': 'M6C 1B2',
'province': '',
'url': 'http://www.wychwoodopendoor.org'},
{'address_1': '7 Vanauley St',
'city': 'Toronto',
'eligibility': 'Youth',
'email': ' ',
'latitude': '43.648869',
'location_type': 'Drop-in',
'longitude': '-79.398283',
'name': 'Youth Drop-in ',
'phone_number': '4166036366',
'postal_code': 'M5T 2V9',
'province': 'ON',
'url': 'http://www.ymcagta.org'},
{'address_1': '40 Teesdale Pl, Gr Fl',
'city': 'Toronto',
'eligibility': 'Mixed Adults',
'email': '',
'latitude': '43.6972002',
'location_type': 'Drop-in',
'longitude': '-79.2866467',
'name': 'Helping Hands Drop-in Centre',
'phone_number': '4166941138',
'postal_code': 'M1L 1L3',
'province': 'ON',
'url': 'http://www.wardenwoods.com'},
{'address_1': '202 Markham Rd',
'city': 'Toronto',
'eligibility': 'Mixed Adults',
'email': 'info@agincourtcommunityservices.com',
'latitude': '43.743773',
'location_type': 'Drop-in',
'longitude': '-79.219741',
'name': 'Scarborough Drop-in South',
'phone_number': '4162670115',
'postal_code': 'M1J 3C2',
'province': 'ON',
'url': 'http://www.agincourtcommunityservices.com'},
{'address_1': 'Adelaide Resource Centre for Women, 3rd Fl 67 Adelaide St E  Toronto ',
'city': 'ON',
'eligibility': 'Women',
'email': '',
'latitude': '43.650986',
'location_type': 'Drop-in',
'longitude': '-79.375299',
'name': "Women's Art Afternoon",
'phone_number': '4163642261',
'postal_code': '1K6 ',
'province': 'M5C',
'url': 'http://www.regentparkchc.org'}]

TORONTO_HOMELESS_SHELTERS += TORONTO_OUT_OF_THE_COLD_CENTERS
TORONTO_HOMELESS_SHELTERS += TORONTO_HOUSING_HELP
TORONTO_HOMELESS_SHELTERS += TORONTO_RESPITE_SITES
TORONTO_HOMELESS_SHELTERS += TORONTO_DROP_INS

TORONTO_HOMELESS_SHELTERS.each do |shelter|
  puts shelter
  if shelter[:address_1].include? 'Toronto'
    shelter[:address_1] = shelter[:address_1].sub('Toronto', '')
    shelter[:city] = 'Toronto'
    shelter[:province] = 'ON'
  elsif shelter[:city].include? 'Toronto'
    shelter[:province] = 'ON'
  end
end

# Location.create(TORONTO_HOMELESS_SHELTERS)